row.set("ActionCount",Integer.valueOf(values[0]));
       row.set("ActionDuration",Integer.valueOf(values[0]));
       row.set("ActionName",new String(values[1]));
       row.set("ActionType",new String(values[2]));
       row.set("ActiveViewEligibleImpression",new String(values[3]));
       row.set("AdUnitId",new String(values[4]));
       row.set("Advertiser",new String(values[5]));
       row.set("AdvertiserId",new String(values[6]));
       row.set("AdxAccountId",new String(values[7]));
       row.set("Anonymous",new String(values[8]));
       row.set("AuctionType",new String(values[9]));
       row.set("Bandwidth",new String(values[10]));
       row.set("BandwidthGroupId",new String(values[10]));
       row.set("BidAdvertiser",new String(values[11]));
       row.set("BidBidder",new String(values[12]));
       row.set("BidBuyer",new String(values[13]));
       row.set("BidDealId",Integer.valueOf(values[0]));
       row.set("BidDealType",new String(values[13]));
       row.set("BidPrice",Integer.valueOf(values[0]));
       row.set("BidRejectionReason",new String(values[13]));
       row.set("BidYieldGroupCompanyId",new String(values[13]));
       row.set("BidYieldGroupNames",new String(values[13]));
       row.set("Browser",new String(values[13]));
       row.set("BrowserId",new String(values[13]));
       row.set("Buyer",new String(values[13]));
       row.set("City",new String(values[13]));
       row.set("CityId",new String(values[13]));
       row.set("Country",new String(values[13]));
       row.set("CountryId",new String(values[13]));
       row.set("CreativeId",Integer.valueOf(values[0]));
       row.set("CreativeSize",Integer.valueOf(values[0]));
       row.set("CreativeVersion",Integer.valueOf(values[0]));
       row.set("CustomTargeting",new String(values[13]));
       row.set("DealId",Integer.valueOf(values[0]));
       row.set("DealType",new String(values[13]));
       row.set("DeviceCategory",new String(values[13]));
       row.set("Domain",new String(values[13]));
       row.set("EstimatedBackfillRevenue",Integer.valueOf(values[0]));
       row.set("Domain",new String(values[13]));
       row.set("EventKeyPart",new String(values[39]));
       row.set("EventTimeUsec2",new String(values[40]));
       row.set("EventDate",new Date(values[41]));
       
